### ISSUE TITLE
Problem with sending this ecrypy to email

### ISSUE THREAD

**Issue by popinbxdgh** [XMB5/HtmlVault#1]
Problem with sending this ecrypy to email i got this message Error: Malformed UTF-8 data

**Comment by XMB5** [comment]
I'm not sure what you mean. Can you provide some more context as to how you are using HtmlVault? Perhaps some test files too? That will help a lot

**Comment by popinbxdgh** [comment]
I went to use this tools before sending emails

**Comment by XMB5** [comment]
You should use GPG for encrypting emails.

If you want to use HtmlVault, you would need to create an HTML file with your message, encrypt it with HtmlVault, upload the encrypted version to github pages, and share a link the the encrypted page.
